-- =============================================================================
-- Enrich brand_info with manually-curated data for the top-tier global tire
-- brands. Skipped: Pirelli, Continental, Hankook (already curated).
--
-- Data sources are public (Wikipedia, manufacturer websites). Descriptions
-- are short editorial blurbs — 1-2 sentences aimed at a fleet operator
-- browsing the marketplace brand page.
--
-- Logo URLs use Clearbit's free brand-logo endpoint (`/logo.clearbit.com/
-- {domain}`) which returns a PNG. If Clearbit ever paywalls, admins can
-- swap individual URLs via the /brand-info admin edit panel.
--
-- Idempotent: UPDATE on slug, so re-running refreshes fields without
-- duplicating rows. Admin-edited fields (primaryColor, accentColor,
-- heroImageUrl, tagline) are NOT overwritten if they've been customized.
--
-- Usage:
--   psql "$DATABASE_URL" -f scripts/enrich-brand-info.sql
-- =============================================================================

BEGIN;

-- Temp staging so we can update in one pass per row.
CREATE TEMP TABLE brand_seed (
  slug           TEXT PRIMARY KEY,
  name           TEXT,
  logo_url       TEXT,
  country        TEXT,
  headquarters   TEXT,
  founded_year   INTEGER,
  website        TEXT,
  description    TEXT,
  tier           TEXT,
  tagline        TEXT,
  parent_company TEXT,
  primary_color  TEXT,
  accent_color   TEXT
);

INSERT INTO brand_seed VALUES
-- ═══ PREMIUM (global top tier) ══════════════════════════════════════════════
('michelin',
  'Michelin',
  'https://logo.clearbit.com/michelin.com',
  'Francia',
  'Clermont-Ferrand, Francia',
  1889,
  'https://www.michelin.com',
  'Fabricante francés líder mundial en neumáticos de alto desempeño. Reconocido por su tecnología de banda de rodadura y su enfoque en longevidad, seguridad y eficiencia de combustible.',
  'premium',
  'Innovación y durabilidad francesa desde 1889',
  NULL,
  '#0033A0',
  '#FFCC00'),

('goodyear',
  'Goodyear',
  'https://logo.clearbit.com/goodyear.com',
  'Estados Unidos',
  'Akron, Ohio, EE. UU.',
  1898,
  'https://www.goodyear.com',
  'Una de las empresas de neumáticos más grandes del mundo, con presencia en más de 22 países. Conocida por su gama Wrangler para camión y pickup, y Assurance para pasajeros.',
  'premium',
  'Tecnología estadounidense para cada camino',
  NULL,
  '#FFCC00',
  '#0033A0'),

('bridgestone',
  'Bridgestone',
  'https://logo.clearbit.com/bridgestone.com',
  'Japón',
  'Tokio, Japón',
  1931,
  'https://www.bridgestone.com',
  'Mayor fabricante mundial de neumáticos por ingresos. Fuerte en camiones comerciales, buses y flotas pesadas, con tecnología Ecopia para menor resistencia al rodamiento.',
  'premium',
  'Desempeño japonés líder a nivel mundial',
  NULL,
  '#E30613',
  '#000000'),

('dunlop',
  'Dunlop',
  'https://logo.clearbit.com/dunlop.eu',
  'Reino Unido',
  'Birmingham, Reino Unido',
  1889,
  'https://www.dunlopeu.com',
  'Marca histórica británica operada globalmente por Sumitomo Rubber. Famosa por sus compuestos deportivos y su herencia en motocicletas y vehículos de alto desempeño.',
  'premium',
  'Herencia británica en neumáticos desde 1889',
  'Sumitomo Rubber Industries',
  '#FFD700',
  '#000000'),

-- ═══ MID-TIER (global manufacturers) ════════════════════════════════════════
('yokohama',
  'Yokohama',
  'https://logo.clearbit.com/yokohama.com',
  'Japón',
  'Tokio, Japón',
  1917,
  'https://www.yokohamatire.com',
  'Fabricante japonés con más de 100 años. Línea Geolandar para SUV y camioneta, Advan para desempeño deportivo, y gama comercial 103ZR ampliamente usada en flotas colombianas.',
  'mid',
  'Ingeniería japonesa confiable',
  NULL,
  '#CE1126',
  '#000000'),

('kumho',
  'Kumho',
  'https://logo.clearbit.com/kumhotire.com',
  'Corea del Sur',
  'Gwangju, Corea del Sur',
  1960,
  'https://www.kumhotire.com',
  'Fabricante coreano con amplia gama para pasajeros y camiones. Buena relación precio-calidad y presencia creciente en mercados latinoamericanos.',
  'mid',
  'Calidad coreana a precio justo',
  NULL,
  '#E2231A',
  '#0032A0'),

('toyo',
  'Toyo',
  'https://logo.clearbit.com/toyotires.com',
  'Japón',
  'Osaka, Japón',
  1945,
  'https://www.toyotires.com',
  'Especialista japonés en compuestos de larga duración. Línea Proxes para pasajeros premium y M-155 / M-154 para camiones comerciales.',
  'mid',
  'Durabilidad japonesa en cada kilómetro',
  NULL,
  '#E60027',
  '#000000'),

('falken',
  'Falken',
  'https://logo.clearbit.com/falken.com',
  'Japón',
  'Hyōgo, Japón',
  1983,
  'https://www.falkentire.com',
  'Marca deportiva de Sumitomo Rubber. Popular en SUV, pickup y mercado de reemplazo por su agarre en mojado y precio competitivo frente a premium.',
  'mid',
  'Desempeño deportivo accesible',
  'Sumitomo Rubber Industries',
  '#0066B3',
  '#E60012'),

('nexen',
  'Nexen',
  'https://logo.clearbit.com/nexentire.com',
  'Corea del Sur',
  'Yangsan, Corea del Sur',
  1942,
  'https://www.nexentire.com',
  'Fabricante coreano con enfoque en innovación y valor. Gama Roadian para SUV / camioneta y CP / N8000 para pasajeros urbanos.',
  'mid',
  'Innovación coreana en cada vía',
  NULL,
  '#E60012',
  '#000000'),

('firestone',
  'Firestone',
  'https://logo.clearbit.com/firestone.com',
  'Estados Unidos',
  'Nashville, Tennessee, EE. UU.',
  1900,
  'https://www.firestonetire.com',
  'Marca histórica estadounidense, hoy parte del grupo Bridgestone. Fuerte presencia en camión comercial FS400 / FD663 y línea Destination para pickup.',
  'mid',
  'Experiencia americana en camión pesado',
  'Bridgestone',
  '#EE1C2E',
  '#FFFFFF'),

('general',
  'General Tire',
  'https://logo.clearbit.com/generaltire.com',
  'Estados Unidos',
  'Fort Mill, Carolina del Sur, EE. UU.',
  1915,
  'https://www.generaltire.com',
  'Marca estadounidense del grupo Continental enfocada en camioneta y trabajo pesado. Línea Grabber para SUV/offroad y HD2 / HS para camión.',
  'mid',
  'Fuerza americana para trabajo duro',
  'Continental',
  '#E4002B',
  '#0033A0'),

('bfgoodrich',
  'BFGoodrich',
  'https://logo.clearbit.com/bfgoodrichtires.com',
  'Estados Unidos',
  'Greenville, Carolina del Sur, EE. UU.',
  1870,
  'https://www.bfgoodrichtires.com',
  'Marca del grupo Michelin especializada en offroad y pickup. La línea All-Terrain T/A KO2 es referencia global en 4x4.',
  'mid',
  'El rey del offroad americano',
  'Michelin',
  '#E30613',
  '#000000'),

('laufenn',
  'Laufenn',
  'https://logo.clearbit.com/laufenn.com',
  'Corea del Sur',
  'Daejeon, Corea del Sur',
  2014,
  'https://www.laufenn.com',
  'Marca moderna del grupo Hankook con enfoque en simplicidad y valor. Línea G-FIT para pasajeros urbanos y X-FIT para SUV.',
  'mid',
  'Hankook calidad, precio económico',
  'Hankook',
  '#00529C',
  '#E30613'),

('maxxis',
  'Maxxis',
  'https://logo.clearbit.com/maxxis.com',
  'Taiwán',
  'Yuanlin, Taiwán',
  1967,
  'https://www.maxxis.com',
  'Fabricante taiwanés reconocido por su gama de SUV, camioneta y motocicleta. Bravo y Razr son sus líneas de referencia para offroad.',
  'mid',
  'Aventura taiwanesa todo terreno',
  NULL,
  '#E60012',
  '#000000'),

('nitto',
  'Nitto',
  'https://logo.clearbit.com/nittotire.com',
  'Japón',
  'Osaka, Japón',
  1949,
  'https://www.nittotire.com',
  'Marca del grupo Toyo enfocada en estilo y desempeño. Línea Ridge Grappler y Recon Grappler para pickup offroad, Motivo para tuning urbano.',
  'mid',
  'Estilo japonés con carácter',
  'Toyo Tire',
  '#000000',
  '#FFCC00'),

('cooper',
  'Cooper',
  'https://logo.clearbit.com/coopertire.com',
  'Estados Unidos',
  'Findlay, Ohio, EE. UU.',
  1914,
  'https://www.coopertire.com',
  'Fabricante centenario del grupo Goodyear. Reconocido por sus CS5 / Discoverer para SUV y camioneta, con buena duración y confort.',
  'mid',
  'Tradición americana confiable',
  'Goodyear',
  '#ED1C24',
  '#000000'),

('uniroyal',
  'Uniroyal',
  'https://logo.clearbit.com/uniroyal.com',
  'Estados Unidos',
  'Greenville, Carolina del Sur, EE. UU.',
  1892,
  'https://www.uniroyaltires.com',
  'Marca estadounidense del grupo Michelin, especializada en agarre en mojado. Tiger Paw para pasajeros, Laredo para pickup.',
  'mid',
  'El tigre en tus ruedas',
  'Michelin',
  '#F7941D',
  '#000000'),

('sumitomo',
  'Sumitomo',
  'https://logo.clearbit.com/sumitomotire.com',
  'Japón',
  'Kobe, Japón',
  1913,
  'https://www.sumitomotire.com',
  'Corporación japonesa matriz de Falken y Dunlop. Su propia línea HTR para pasajeros y ST-728 para camión se vende globalmente.',
  'mid',
  'Gigante industrial japonés',
  NULL,
  '#EC1C24',
  '#000000'),

('giti',
  'Giti',
  'https://logo.clearbit.com/giti.com',
  'Singapur',
  'Singapur',
  1951,
  'https://www.giti.com',
  'Uno de los mayores fabricantes asiáticos, con plantas en China, Indonesia y EE. UU. Amplia gama en camión de carga, bus y pasajeros. Muy presente en flotas colombianas.',
  'mid',
  'Cobertura global, precio competitivo',
  NULL,
  '#E30613',
  '#FFFFFF'),

('roadstone',
  'Roadstone',
  'https://logo.clearbit.com/nexentire.com',
  'Corea del Sur',
  'Yangsan, Corea del Sur',
  1942,
  'https://www.nexentire.com',
  'Marca hermana de Nexen, enfocada en mercados de reemplazo. Mismos estándares de fábrica, línea orientada a valor.',
  'mid',
  'Valor coreano para flotas',
  'Nexen Tire',
  '#E60012',
  '#000000'),

-- ═══ VALUE (Chinese + regional) ═════════════════════════════════════════════
('triangle',
  'Triangle',
  'https://logo.clearbit.com/triangletire.com',
  'China',
  'Weihai, Shandong, China',
  1976,
  'https://www.triangletire.com',
  'Uno de los mayores fabricantes chinos. Gama TR659 / TR685 ampliamente vista en buses y camión de carga colombiano por su relación precio-km.',
  'value',
  'Volumen chino para flota',
  NULL,
  '#003DA5',
  '#E30613'),

('linglong',
  'Linglong',
  'https://logo.clearbit.com/linglong.com',
  'China',
  'Zhaoyuan, Shandong, China',
  1975,
  'https://www.linglong.com',
  'Fabricante chino con OEM en Ford, VW y Renault. Gama Green-Max para pasajeros y D901 para camión comercial, competitivos en precio.',
  'value',
  'OEM chino de escala global',
  NULL,
  '#E4002B',
  '#FFFFFF'),

('doublecoin',
  'Double Coin',
  'https://logo.clearbit.com/doublecointires.com',
  'China',
  'Shanghái, China',
  1983,
  'https://www.doublecointires.com',
  'Especialista chino en camión comercial. RR150 / RLB200 son referencias comunes en tractomula por su costo-beneficio.',
  'value',
  'Camión pesado a precio chino',
  NULL,
  '#E60012',
  '#FFD700'),

('westlake',
  'Westlake',
  'https://logo.clearbit.com/westlaketires.com',
  'China',
  'Hangzhou, Zhejiang, China',
  1958,
  'https://www.westlaketires.com',
  'Marca principal de ZC Rubber, uno de los mayores productores chinos. Gama amplia en camioneta, camión y pasajeros, muy presente en Colombia.',
  'value',
  'Presencia china masiva en Colombia',
  'ZC Rubber',
  '#003DA5',
  '#E30613'),

('goodride',
  'Goodride',
  'https://logo.clearbit.com/goodride.com',
  'China',
  'Hangzhou, Zhejiang, China',
  1958,
  'https://www.goodride.com',
  'Marca hermana de Westlake (ZC Rubber). Popular en camión de carga con CR926 y pasajeros con SU318.',
  'value',
  'Calidad china económica',
  'ZC Rubber',
  '#E4002B',
  '#000000'),

('sunfull',
  'Sunfull',
  'https://logo.clearbit.com/sunfulltire.com',
  'China',
  'Shandong, China',
  2004,
  'https://www.sunfulltire.com',
  'Fabricante chino enfocado en mercado latinoamericano. HF805 para camión y HF201 para pasajeros son sus líneas de mayor rotación.',
  'value',
  'Especialista en América Latina',
  NULL,
  '#EC1C24',
  '#000000'),

('aplus',
  'Aplus',
  'https://logo.clearbit.com/aplus-tire.com',
  'China',
  'Qingdao, Shandong, China',
  2006,
  'https://www.aplus-tire.com',
  'Marca china enfocada en valor. Amplia gama para camión y pickup, con fuerte presencia en el mercado de reemplazo colombiano.',
  'value',
  'Llanta china accesible',
  NULL,
  '#E60012',
  '#FFFFFF'),

('doublestar',
  'Double Star',
  'https://logo.clearbit.com/doublestartire.com',
  'China',
  'Qingdao, China',
  1921,
  'https://www.doublestartire.com',
  'Fabricante centenario chino. Líneas DSR para camión y DS602 para pasajeros, con distribución internacional consolidada.',
  'value',
  'Siglo de experiencia china',
  NULL,
  '#003DA5',
  '#FFD700'),

('kpatos',
  'Kpatos',
  'https://logo.clearbit.com/kpatos.com',
  'China',
  'Qingdao, China',
  2010,
  NULL,
  'Marca china de creciente presencia en Colombia. Enfoque en camión comercial de carga con buen costo por kilómetro.',
  'value',
  'Costo por km competitivo',
  NULL,
  '#E30613',
  '#000000'),

('chengshang',
  'Chengshan',
  NULL,
  'China',
  'Rongcheng, Shandong, China',
  1986,
  NULL,
  'Fabricante chino (CST) con gran volumen en camión y bus. Muy presente en tractomulas colombianas por su precio agresivo.',
  'value',
  'Volumen chino para transporte',
  NULL,
  '#003DA5',
  '#E60012'),

('zeta',
  'Zeta',
  'https://logo.clearbit.com/zetatires.com',
  'China',
  'Shandong, China',
  2008,
  'https://www.zetatires.com',
  'Marca china orientada a mercado latino. Amplia gama para camioneta, pickup y automóvil a precio accesible.',
  'value',
  'Opción china para toda flota',
  NULL,
  '#E4002B',
  '#FFFFFF'),

('roadshine',
  'Roadshine',
  'https://logo.clearbit.com/roadshinetire.com',
  'China',
  'Shandong, China',
  2006,
  'https://www.roadshinetire.com',
  'Especialista chino en camión de carga pesada. RS620 / RS652 presentes en flotas de larga distancia en Colombia.',
  'value',
  'Carga pesada, precio ligero',
  NULL,
  '#E30613',
  '#000000'),

('jinyu',
  'Jinyu',
  'https://logo.clearbit.com/jinyutire.com',
  'China',
  'Taiyuan, Shanxi, China',
  1996,
  'https://www.jinyutire.com',
  'Fabricante chino con foco en camión comercial. Gama JY712 / JD755 frecuente en transporte urbano y regional.',
  'value',
  'Transporte comercial chino',
  NULL,
  '#E60012',
  '#FFFFFF'),

('longmarch',
  'Long March',
  'https://logo.clearbit.com/longmarchtyre.com',
  'China',
  'Shuangliao, Jilin, China',
  1956,
  'https://www.longmarchtyre.com',
  'Marca histórica china (Long March Tire Co.). LM216 / LM508 populares en camión comercial por su durabilidad kilométrica.',
  'value',
  'Tradición china de carga pesada',
  NULL,
  '#E30613',
  '#FFD700'),

('annaite',
  'Annaite',
  'https://logo.clearbit.com/annaite-tyre.com',
  'China',
  'Jiangsu, China',
  1994,
  NULL,
  'Fabricante chino de camión comercial. Gama AM08 / AM15 con precio agresivo para flota de larga distancia.',
  'value',
  'Kilómetros chinos económicos',
  NULL,
  '#003DA5',
  '#E4002B'),

('onyx',
  'Onyx',
  NULL,
  'China',
  'China',
  2000,
  NULL,
  'Marca china de valor enfocada en pasajeros y SUV urbano. Presencia en mercado de reemplazo colombiano.',
  'value',
  'Valor chino para ciudad',
  NULL,
  '#000000',
  '#E60012'),

('aeolus',
  'Aeolus',
  'https://logo.clearbit.com/aeolus-tyre.com',
  'China',
  'Jiaozuo, Henan, China',
  1965,
  'https://www.aeolus-tyre.com',
  'Gran fabricante chino especializado en camión y OTR (fuera de carretera). HN306 / HN309 vistos en tractomulas colombianas.',
  'value',
  'Camión y OTR a escala china',
  NULL,
  '#E30613',
  '#FFFFFF'),

('techshield',
  'Techshield',
  NULL,
  'China',
  'China',
  2015,
  NULL,
  'Marca china económica de distribución regional. Líneas para pasajeros y camioneta urbana.',
  'value',
  'Economía china moderna',
  NULL,
  '#0066B3',
  '#000000');

-- -----------------------------------------------------------------------------
-- Apply the seed. Only update rows that have our auto-seed marker
-- (source='catalog') OR are matching one of these slugs explicitly — that
-- way admin-curated rows keep their customizations.
-- -----------------------------------------------------------------------------
UPDATE brand_info b
SET
  -- Don't touch `name` — it has a UNIQUE constraint and the initial seed
  -- already set it via INITCAP(). Slug is the URL key; name is just
  -- display, already good enough. Avoids spurious conflicts like
  -- "chengshang" slug trying to become name "Chengshan" while another
  -- row already owns that name.
  "logoUrl"     = COALESCE(b."logoUrl",     s.logo_url),
  country       = COALESCE(b.country,       s.country),
  headquarters  = COALESCE(b.headquarters,  s.headquarters),
  "foundedYear" = COALESCE(b."foundedYear", s.founded_year),
  website       = COALESCE(b.website,       s.website),
  description   = COALESCE(b.description,   s.description),
  tier          = s.tier,
  tagline       = COALESCE(b.tagline,       s.tagline),
  "parentCompany" = COALESCE(b."parentCompany", s.parent_company),
  "primaryColor"  = COALESCE(b."primaryColor",  s.primary_color),
  "accentColor"   = COALESCE(b."accentColor",   s.accent_color),
  source        = CASE WHEN b.source IN ('catalog', 'manual', NULL) THEN 'manual' ELSE b.source END,
  "updatedAt"   = NOW()
FROM brand_seed s
WHERE b.slug = s.slug
  -- Never overwrite Pirelli / Continental / Hankook — user explicitly
  -- asked to leave these alone.
  AND b.slug NOT IN ('pirelli', 'continental', 'hankook');

COMMIT;
